### ISSUE TITLE
include layer bbox on layer service response

### ISSUE THREAD

**Issue by miguelpeixe** [ecodigital/DomeGIS#17]

**Comment by miguelpeixe** [comment]
`extents` and `featureCount` are `null` on object response

**Comment by vgeorge** [comment]
Extents and features count are available after message "syncFinish" is emitted, not after "created" message.

**Comment by miguelpeixe** [comment]
its intermitent, some layers work others don't

just tested `2015524_Pa_Amur_China` and the extent is null.

on the other hand, `Tapajos_limit_storymap` worked as well as `ibge_cities_2009_storymap`

**Comment by vgeorge** [comment]
Now bbox is set for `2015524_Pa_Amur_China`.
