### ISSUE TITLE
fatal error while editing view cartocss

### ISSUE THREAD

**Issue by miguelpeixe** [ecodigital/DomeGIS#26]
happened on homolog env while changing the color (live map updates) for a `point` layer:

```
TypeError: Cannot set property 'grainstore' of undefined
    at EventEmitter.module.exports (/root/DomeGIS/src/services/tiles-new/index.js:32:19)
```

**Comment by vgeorge** [comment]
error while editing layer KAZA_protected_areas

**Comment by miguelpeixe** [comment]
this issue could be related to trying to create map without the sync being complete, there should be proper callback that doesn't crash the server
