### ISSUE TITLE
error while syncing

### ISSUE THREAD

**Issue by miguelpeixe** [ecodigital/DomeGIS#32]
`tapajos_vegation`
`tapajos_roads`

error:
```
TypeError: Cannot read property 'length' of undefined
    at Request._callback (/vagrant/src/services/layer/hooks/index.js:244:31)
```

**Comment by miguelpeixe** [comment]
could be layer Tapajos_lulc_2012_storymap (from Layer 2 - Tapajos vegetation data) or Tapajos_roads_storymap (from Tapajos main roads data)

**Comment by vgeorge** [comment]
ArcGIS can't generate a valid GeoJSON probably because multipolygon features are too big. Layer property `status` is set to `failed_sync`.
