### ISSUE TITLE
Sync failure when geometry is null

### ISSUE THREAD

**Issue by bwstefano** [ecodigital/DomeGIS#41]
When synced, "Amazon_def_fronts" layer won't show edit layer or create view buttons

**Comment by vgeorge** [comment]
The [last geometry](
http://services1.arcgis.com/RTK5Unh1Z71JKIiR/arcgis/rest/services/Amazon_def_fronts/FeatureServer/0/query?where=1%3D1&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=&units=esriSRUnit_Meter&outFields=&returnGeometry=true&returnCentroid=false&multipatchOption=&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnDistinctValues=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&quantizationParameters=&sqlFormat=none&f=pgeojson&token=) of this layer is `null`, causing a sync fail.
