### ISSUE TITLE
derived layers don't have domegis_id

### ISSUE THREAD

**Issue by miguelpeixe** [ecodigital/DomeGIS#47]
causing error while trying to create styles:

```
[Error: Postgis Plugin: ERROR:  column "domegis_id" does not exist
LINE 1: SELECT * FROM (select domegis_id, geometry  from "055ad317a2...
                              ^

in executeQuery Full sql was: 'SELECT * FROM (select domegis_id, geometry  from "055ad317a2d85285a91a3a19a9be24db337a76ac") as cdbq LIMIT 0'
  encountered during parsing of layer 'layer0' in Layer]
```

**Comment by vgeorge** [comment]
It worked for me when I select `domegis_id` while creating a new layer. Maybe we should enforce `domegis_id` existence while creating a derived layer, as we do to geometry field.

**Comment by vgeorge** [comment]
Or create a primaryKey field, but this would require a bigger refactor.

**Comment by miguelpeixe** [comment]
domegis_id should be created automatically, not inherited.

custom queries can create custom filtered/modified/merged features that shouldn't inherit id from other layers, potentially causes conflict from duplicate ids.

**Comment by vgeorge** [comment]
Now it generates derived layer own's `domegis_id`.
