### ISSUE TITLE
attached meta to geographic table feature

### ISSUE THREAD

**Issue by miguelpeixe** [ecodigital/DomeGIS#5]
there should be a model for attached meta on a table's feature

**`attached_meta`** model:
```json
{
  "name": "string",
  "value": "string",
  "table": "table_id",
  "table_column": "table column to identify feature key by",
  "feature_val": "table feature val to identify by"
}
````

`value` is supposed to work as url for file download or regular text.

better approach to find the feature is welcome (`table_column`:`feature_val` doesnt seem the best approach)

cc @vgeorge

**Comment by miguelpeixe** [comment]
if the geographic table has a default and cross-table column for id, there will be no need to use `table_column` column on the attached meta

**Comment by vgeorge** [comment]
All features belonging to a layer [have an *objectId*](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Add_Features/02r30000010m000000/), so they can be uniquely identified.

Also, Sequelize has [support to BLOB fields](http://docs.sequelizejs.com/en/1.7.0/docs/models/#data-types), so media can be stored in the database.

**Comment by miguelpeixe** [comment]
the media itself? isn't that too much for database storage?

**Comment by vgeorge** [comment]
As discussed, the best strategy seems to have separated tables for additional feature metas, which will be joined to geo-tables in a SQL statement passed to Windshaft to generate tiles and utf grid layers.
